import { StyleSheet, Font } from "@react-pdf/renderer";

Font.register({
	family: "YoonGothic",
	src: "https://cdn.jsdelivr.net/font-nanumlight/1.0/NanumBarunGothicWeb.ttf",
});

export const styles = StyleSheet.create({
	viewer: {
		position: "relative",
		left: 100,
		width: 980,
		height: 863,
	},
	image: {
		marginLeft: -30,
		marginTop: -50,
		position: "relative",
	},
	text__name: {
		fontFamily: "YoonGothic",
		position: "absolute",
		left: 180,
		top: 209,
		width: 110,
		height: 24,
		textAlign: "center",
		paddingTop: 5,
		fontSize: 13,
	},
	text__birthday: {
		fontFamily: "YoonGothic",
		position: "absolute",
		left: 180,
		top: 234,
		width: 110,
		height: 24,
		textAlign: "center",
		paddingTop: 5,
		fontSize: 13,
	},
	text__numbers: {
		fontFamily: "YoonGothic",
		position: "absolute",
		left: 180,
		top: 259,
		width: 110,
		height: 24,
		textAlign: "center",
		paddingTop: 5,
		fontSize: 13,
	},
	text__position: {
		fontFamily: "YoonGothic",
		position: "absolute",
		left: 180,
		top: 284,
		width: 110,
		height: 24,
		textAlign: "center",
		paddingTop: 5,
		fontSize: 13,
	},
	text__gender: {
		fontFamily: "YoonGothic",
		position: "absolute",
		left: 370,
		top: 209,
		width: 150,
		height: 24,
		textAlign: "center",
		paddingTop: 5,
		fontSize: 13,
	},
	text__email: {
		fontFamily: "YoonGothic",
		position: "absolute",
		left: 370,
		top: 234,
		width: 150,
		height: 24,
		textAlign: "center",
		paddingTop: 5,
		fontSize: 13,
	},
	text__company: {
		fontFamily: "YoonGothic",
		position: "absolute",
		left: 370,
		top: 259,
		width: 150,
		height: 24,
		textAlign: "center",
		paddingTop: 5,
		fontSize: 13,
	},
	text__job: {
		fontFamily: "YoonGothic",
		position: "absolute",
		left: 370,
		top: 284,
		width: 150,
		height: 24,
		textAlign: "center",
		paddingTop: 5,
		fontSize: 13,
	},
	text__academic__year1:{
		fontFamily: "YoonGothic",
		position: "absolute",
		top: 366,
		left: 43,
		width: 150,
		height: 24,
		textAlign: "center",
		paddingTop: 5,
		fontSize: 13,
	},
	text__academic__year2:{
		fontFamily: "YoonGothic",
		position: "absolute",
		top: 386,
		left: 43,
		width: 150,
		height: 24,
		textAlign: "center",
		paddingTop: 5,
		fontSize: 13,
	},
	text__academic__school:{
		fontFamily: "YoonGothic",
		position: "absolute",
		top: 366,
		left: 150,
		width: 40,
		height: 24,
		textAlign: "center",
		paddingTop: 5,
		fontSize: 13,
	},
	text__academic__university:{
		fontFamily: "YoonGothic",
		position: "absolute",
		top: 386,
		left: 150,
		width: 40,
		height: 24,
		textAlign: "center",
		paddingTop: 5,
		fontSize: 13,
	},
	text__academic__university_department:{
		fontFamily: "YoonGothic",
		position: "absolute",
		top: 386,
		left: 233,
		width: 40,
		height: 24,
		textAlign: "center",
		paddingTop: 5,
		fontSize: 13,
	},
	text__sign__year: {
		fontFamily: "YoonGothic",
		position: "absolute",
		left: 365,
		top: 595,
		width: 100,
		height: 24,
		textAlign: "center",
		paddingTop: 5,
		fontSize: 13,
	},
	text__sign__month: {
		fontFamily: "YoonGothic",
		position: "absolute",
		left: 408,
		top: 595,
		width: 100,
		height: 24,
		textAlign: "center",
		paddingTop: 5,
		fontSize: 13,
	},
	text__sign__day: {
		fontFamily: "YoonGothic",
		position: "absolute",
		left: 440,
		top: 595,
		width: 100,
		height: 24,
		textAlign: "center",
		paddingTop: 5,
		fontSize: 13,
	},
	text__sign__name:{
		fontFamily: "YoonGothic",
		position: "absolute",
		left: 379,
		top: 613,
		width: 100,
		height: 24,
		textAlign: "center",
		paddingTop: 5,
		fontSize: 13,
	},
	checkImg__military1: {
		width: 13,
		height: 13,
		position: "absolute",
		top: 320,
		left: 111,
	},
	checkImg__military2: {
		width: 13,
		height: 13,
		position: "absolute",
		top: 320,
		left: 331,
	},
	checkImg__military3: {
		width: 13,
		height: 13,
		position: "absolute",
		top: 320,
		left: 390,
	},
	checkImg__military4: {
		width: 13,
		height: 13,
		position: "absolute",
		top: 320,
		left: 449,
	},
	checkImg__military5: {
		width: 13,
		height: 13,
		position: "absolute",
		top: 340,
		left: 111,
	},
	checkImg__academic1: {
		width: 13,
		height: 13,
		position: "absolute",
		top: 370,
		left: 336.5,
	},
	checkImg__academic2: {
		width: 13,
		height: 13,
		position: "absolute",
		top: 370,
		left: 390,
	},
	checkImg__academic3: {
		width: 13,
		height: 13,
		position: "absolute",
		top: 370,
		left: 465,
	},
	checkImg__academic4: {
		width: 13,
		height: 13,
		position: "absolute",
		top: 390,
		left: 336.5,
	},
	checkImg__academic5: {
		width: 13,
		height: 13,
		position: "absolute",
		top: 390,
		left: 390,
	},
	checkImg__academic6: {
		width: 13,
		height: 13,
		position: "absolute",
		top: 390,
		left: 465,
	},
});
